#!/bin/bash

set -e

wget -nc https://download.owncloud.org/community/owncloud-9.0.1.tar.bz2
wget -nc https://download.owncloud.org/community/owncloud-9.0.1.tar.bz2.asc
#gpg --verify owncloud-9.0.1.tar.bz2.asc

tar -xf owncloud-9.0.1.tar.bz2
